#!/usr/bin/env python

import os
import sys

sys.path.insert(0, "../../lib/cbapi/client_apis/python/src/cbapi/")
sys.path.insert(0, "../../lib/src/")

import cbopensource.connectors.fidelis.bridge as bridge
import cbopensource.connectors.fidelis.version as version

if __name__ == "__main__":
    my_path = os.path.dirname(os.path.abspath(__file__))
    temp_directory = "/tmp/fidelis"
    logfile = os.path.join(temp_directory,"test.log")
    name = "carbonblack_fidelis_bridge"
    daemon = bridge.CarbonBlackFidelisBridge(name, configfile=os.path.join(my_path,"testing.conf"),logfile=logfile)
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, version.__version__)
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

